// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: jsonpackethead.proto

#ifndef PROTOBUF_jsonpackethead_2eproto__INCLUDED
#define PROTOBUF_jsonpackethead_2eproto__INCLUDED

#include <string>

#include <google/protobuf/stubs/common.h>

#if GOOGLE_PROTOBUF_VERSION < 3002000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please update
#error your headers.
#endif
#if 3002000 < GOOGLE_PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/metadata.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>  // IWYU pragma: export
#include <google/protobuf/extension_set.h>  // IWYU pragma: export
#include <google/protobuf/unknown_field_set.h>
// @@protoc_insertion_point(includes)
namespace jsonpacket {
class JsonPacketHead;
class JsonPacketHeadDefaultTypeInternal;
extern JsonPacketHeadDefaultTypeInternal _JsonPacketHead_default_instance_;
}  // namespace jsonpacket

namespace jsonpacket {

namespace protobuf_jsonpackethead_2eproto {
// Internal implementation detail -- do not call these.
struct TableStruct {
  static const ::google::protobuf::uint32 offsets[];
  static void InitDefaultsImpl();
  static void Shutdown();
};
void AddDescriptors();
void InitDefaults();
}  // namespace protobuf_jsonpackethead_2eproto

// ===================================================================

class JsonPacketHead : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:jsonpacket.JsonPacketHead) */ {
 public:
  JsonPacketHead();
  virtual ~JsonPacketHead();

  JsonPacketHead(const JsonPacketHead& from);

  inline JsonPacketHead& operator=(const JsonPacketHead& from) {
    CopyFrom(from);
    return *this;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const JsonPacketHead& default_instance();

  static inline const JsonPacketHead* internal_default_instance() {
    return reinterpret_cast<const JsonPacketHead*>(
               &_JsonPacketHead_default_instance_);
  }

  void Swap(JsonPacketHead* other);

  // implements Message ----------------------------------------------

  inline JsonPacketHead* New() const PROTOBUF_FINAL { return New(NULL); }

  JsonPacketHead* New(::google::protobuf::Arena* arena) const PROTOBUF_FINAL;
  void CopyFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void MergeFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void CopyFrom(const JsonPacketHead& from);
  void MergeFrom(const JsonPacketHead& from);
  void Clear() PROTOBUF_FINAL;
  bool IsInitialized() const PROTOBUF_FINAL;

  size_t ByteSizeLong() const PROTOBUF_FINAL;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input) PROTOBUF_FINAL;
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const PROTOBUF_FINAL;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* target) const PROTOBUF_FINAL;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output)
      const PROTOBUF_FINAL {
    return InternalSerializeWithCachedSizesToArray(
        ::google::protobuf::io::CodedOutputStream::IsDefaultSerializationDeterministic(), output);
  }
  int GetCachedSize() const PROTOBUF_FINAL { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const PROTOBUF_FINAL;
  void InternalSwap(JsonPacketHead* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return NULL;
  }
  inline void* MaybeArenaPtr() const {
    return NULL;
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const PROTOBUF_FINAL;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // string TypeName = 4;
  void clear_typename_();
  static const int kTypeNameFieldNumber = 4;
  const ::std::string& typename_() const;
  void set_typename_(const ::std::string& value);
  #if LANG_CXX11
  void set_typename_(::std::string&& value);
  #endif
  void set_typename_(const char* value);
  void set_typename_(const char* value, size_t size);
  ::std::string* mutable_typename_();
  ::std::string* release_typename_();
  void set_allocated_typename_(::std::string* typename_);

  // string ProtocolbufData = 5;
  void clear_protocolbufdata();
  static const int kProtocolbufDataFieldNumber = 5;
  const ::std::string& protocolbufdata() const;
  void set_protocolbufdata(const ::std::string& value);
  #if LANG_CXX11
  void set_protocolbufdata(::std::string&& value);
  #endif
  void set_protocolbufdata(const char* value);
  void set_protocolbufdata(const char* value, size_t size);
  ::std::string* mutable_protocolbufdata();
  ::std::string* release_protocolbufdata();
  void set_allocated_protocolbufdata(::std::string* protocolbufdata);

  // int32 Length = 1;
  void clear_length();
  static const int kLengthFieldNumber = 1;
  ::google::protobuf::int32 length() const;
  void set_length(::google::protobuf::int32 value);

  // int32 Flag = 2;
  void clear_flag();
  static const int kFlagFieldNumber = 2;
  ::google::protobuf::int32 flag() const;
  void set_flag(::google::protobuf::int32 value);

  // int32 NameLength = 3;
  void clear_namelength();
  static const int kNameLengthFieldNumber = 3;
  ::google::protobuf::int32 namelength() const;
  void set_namelength(::google::protobuf::int32 value);

  // int32 CheckSum = 6;
  void clear_checksum();
  static const int kCheckSumFieldNumber = 6;
  ::google::protobuf::int32 checksum() const;
  void set_checksum(::google::protobuf::int32 value);

  // @@protoc_insertion_point(class_scope:jsonpacket.JsonPacketHead)
 private:

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::internal::ArenaStringPtr typename__;
  ::google::protobuf::internal::ArenaStringPtr protocolbufdata_;
  ::google::protobuf::int32 length_;
  ::google::protobuf::int32 flag_;
  ::google::protobuf::int32 namelength_;
  ::google::protobuf::int32 checksum_;
  mutable int _cached_size_;
  friend struct  protobuf_jsonpackethead_2eproto::TableStruct;
};
// ===================================================================


// ===================================================================

#if !PROTOBUF_INLINE_NOT_IN_HEADERS
// JsonPacketHead

// int32 Length = 1;
inline void JsonPacketHead::clear_length() {
  length_ = 0;
}
inline ::google::protobuf::int32 JsonPacketHead::length() const {
  // @@protoc_insertion_point(field_get:jsonpacket.JsonPacketHead.Length)
  return length_;
}
inline void JsonPacketHead::set_length(::google::protobuf::int32 value) {
  
  length_ = value;
  // @@protoc_insertion_point(field_set:jsonpacket.JsonPacketHead.Length)
}

// int32 Flag = 2;
inline void JsonPacketHead::clear_flag() {
  flag_ = 0;
}
inline ::google::protobuf::int32 JsonPacketHead::flag() const {
  // @@protoc_insertion_point(field_get:jsonpacket.JsonPacketHead.Flag)
  return flag_;
}
inline void JsonPacketHead::set_flag(::google::protobuf::int32 value) {
  
  flag_ = value;
  // @@protoc_insertion_point(field_set:jsonpacket.JsonPacketHead.Flag)
}

// int32 NameLength = 3;
inline void JsonPacketHead::clear_namelength() {
  namelength_ = 0;
}
inline ::google::protobuf::int32 JsonPacketHead::namelength() const {
  // @@protoc_insertion_point(field_get:jsonpacket.JsonPacketHead.NameLength)
  return namelength_;
}
inline void JsonPacketHead::set_namelength(::google::protobuf::int32 value) {
  
  namelength_ = value;
  // @@protoc_insertion_point(field_set:jsonpacket.JsonPacketHead.NameLength)
}

// string TypeName = 4;
inline void JsonPacketHead::clear_typename_() {
  typename__.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline const ::std::string& JsonPacketHead::typename_() const {
  // @@protoc_insertion_point(field_get:jsonpacket.JsonPacketHead.TypeName)
  return typename__.GetNoArena();
}
inline void JsonPacketHead::set_typename_(const ::std::string& value) {
  
  typename__.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:jsonpacket.JsonPacketHead.TypeName)
}
#if LANG_CXX11
inline void JsonPacketHead::set_typename_(::std::string&& value) {
  
  typename__.SetNoArena(
    &::google::protobuf::internal::GetEmptyStringAlreadyInited(), std::move(value));
  // @@protoc_insertion_point(field_set_rvalue:jsonpacket.JsonPacketHead.TypeName)
}
#endif
inline void JsonPacketHead::set_typename_(const char* value) {
  
  typename__.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:jsonpacket.JsonPacketHead.TypeName)
}
inline void JsonPacketHead::set_typename_(const char* value, size_t size) {
  
  typename__.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:jsonpacket.JsonPacketHead.TypeName)
}
inline ::std::string* JsonPacketHead::mutable_typename_() {
  
  // @@protoc_insertion_point(field_mutable:jsonpacket.JsonPacketHead.TypeName)
  return typename__.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline ::std::string* JsonPacketHead::release_typename_() {
  // @@protoc_insertion_point(field_release:jsonpacket.JsonPacketHead.TypeName)
  
  return typename__.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void JsonPacketHead::set_allocated_typename_(::std::string* typename_) {
  if (typename_ != NULL) {
    
  } else {
    
  }
  typename__.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), typename_);
  // @@protoc_insertion_point(field_set_allocated:jsonpacket.JsonPacketHead.TypeName)
}

// string ProtocolbufData = 5;
inline void JsonPacketHead::clear_protocolbufdata() {
  protocolbufdata_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline const ::std::string& JsonPacketHead::protocolbufdata() const {
  // @@protoc_insertion_point(field_get:jsonpacket.JsonPacketHead.ProtocolbufData)
  return protocolbufdata_.GetNoArena();
}
inline void JsonPacketHead::set_protocolbufdata(const ::std::string& value) {
  
  protocolbufdata_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:jsonpacket.JsonPacketHead.ProtocolbufData)
}
#if LANG_CXX11
inline void JsonPacketHead::set_protocolbufdata(::std::string&& value) {
  
  protocolbufdata_.SetNoArena(
    &::google::protobuf::internal::GetEmptyStringAlreadyInited(), std::move(value));
  // @@protoc_insertion_point(field_set_rvalue:jsonpacket.JsonPacketHead.ProtocolbufData)
}
#endif
inline void JsonPacketHead::set_protocolbufdata(const char* value) {
  
  protocolbufdata_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:jsonpacket.JsonPacketHead.ProtocolbufData)
}
inline void JsonPacketHead::set_protocolbufdata(const char* value, size_t size) {
  
  protocolbufdata_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:jsonpacket.JsonPacketHead.ProtocolbufData)
}
inline ::std::string* JsonPacketHead::mutable_protocolbufdata() {
  
  // @@protoc_insertion_point(field_mutable:jsonpacket.JsonPacketHead.ProtocolbufData)
  return protocolbufdata_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline ::std::string* JsonPacketHead::release_protocolbufdata() {
  // @@protoc_insertion_point(field_release:jsonpacket.JsonPacketHead.ProtocolbufData)
  
  return protocolbufdata_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void JsonPacketHead::set_allocated_protocolbufdata(::std::string* protocolbufdata) {
  if (protocolbufdata != NULL) {
    
  } else {
    
  }
  protocolbufdata_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), protocolbufdata);
  // @@protoc_insertion_point(field_set_allocated:jsonpacket.JsonPacketHead.ProtocolbufData)
}

// int32 CheckSum = 6;
inline void JsonPacketHead::clear_checksum() {
  checksum_ = 0;
}
inline ::google::protobuf::int32 JsonPacketHead::checksum() const {
  // @@protoc_insertion_point(field_get:jsonpacket.JsonPacketHead.CheckSum)
  return checksum_;
}
inline void JsonPacketHead::set_checksum(::google::protobuf::int32 value) {
  
  checksum_ = value;
  // @@protoc_insertion_point(field_set:jsonpacket.JsonPacketHead.CheckSum)
}

#endif  // !PROTOBUF_INLINE_NOT_IN_HEADERS

// @@protoc_insertion_point(namespace_scope)


}  // namespace jsonpacket

// @@protoc_insertion_point(global_scope)

#endif  // PROTOBUF_jsonpackethead_2eproto__INCLUDED
